/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'ui-examples': RouteRecordInfo<'ui-examples', '/examples', Record<never, never>, Record<never, never>>,
    '/examples/button': RouteRecordInfo<'/examples/button', '/examples/button', Record<never, never>, Record<never, never>>,
    '/examples/chart': RouteRecordInfo<'/examples/chart', '/examples/chart', Record<never, never>, Record<never, never>>,
    '/examples/datepicker': RouteRecordInfo<'/examples/datepicker', '/examples/datepicker', Record<never, never>, Record<never, never>>,
    '/examples/file': RouteRecordInfo<'/examples/file', '/examples/file', Record<never, never>, Record<never, never>>,
    '/examples/form': RouteRecordInfo<'/examples/form', '/examples/form', Record<never, never>, Record<never, never>>,
    '/examples/icon-example': RouteRecordInfo<'/examples/icon-example', '/examples/icon-example', Record<never, never>, Record<never, never>>,
    '/examples/popup': RouteRecordInfo<'/examples/popup', '/examples/popup', Record<never, never>, Record<never, never>>,
    '/examples/progress': RouteRecordInfo<'/examples/progress', '/examples/progress', Record<never, never>, Record<never, never>>,
    '/examples/selector': RouteRecordInfo<'/examples/selector', '/examples/selector', Record<never, never>, Record<never, never>>,
    '/examples/table': RouteRecordInfo<'/examples/table', '/examples/table', Record<never, never>, Record<never, never>>,
    '/examples/textfield': RouteRecordInfo<'/examples/textfield', '/examples/textfield', Record<never, never>, Record<never, never>>,
    '/examples/tree': RouteRecordInfo<'/examples/tree', '/examples/tree', Record<never, never>, Record<never, never>>,
  }
}
