/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    'ui-examples': RouteRecordInfo<'ui-examples', '/examples', Record<never, never>, Record<never, never>>,
    '/examples/box': RouteRecordInfo<'/examples/box', '/examples/box', Record<never, never>, Record<never, never>>,
    '/examples/button': RouteRecordInfo<'/examples/button', '/examples/button', Record<never, never>, Record<never, never>>,
    '/examples/carousel': RouteRecordInfo<'/examples/carousel', '/examples/carousel', Record<never, never>, Record<never, never>>,
    '/examples/chart': RouteRecordInfo<'/examples/chart', '/examples/chart', Record<never, never>, Record<never, never>>,
    '/examples/checkbox': RouteRecordInfo<'/examples/checkbox', '/examples/checkbox', Record<never, never>, Record<never, never>>,
    '/examples/control-bar': RouteRecordInfo<'/examples/control-bar', '/examples/control-bar', Record<never, never>, Record<never, never>>,
    '/examples/datepicker': RouteRecordInfo<'/examples/datepicker', '/examples/datepicker', Record<never, never>, Record<never, never>>,
    '/examples/divider': RouteRecordInfo<'/examples/divider', '/examples/divider', Record<never, never>, Record<never, never>>,
    '/examples/dropdown': RouteRecordInfo<'/examples/dropdown', '/examples/dropdown', Record<never, never>, Record<never, never>>,
    '/examples/file': RouteRecordInfo<'/examples/file', '/examples/file', Record<never, never>, Record<never, never>>,
    '/examples/form': RouteRecordInfo<'/examples/form', '/examples/form', Record<never, never>, Record<never, never>>,
    '/examples/g-c-area': RouteRecordInfo<'/examples/g-c-area', '/examples/g-c-area', Record<never, never>, Record<never, never>>,
    '/examples/icon-example': RouteRecordInfo<'/examples/icon-example', '/examples/icon-example', Record<never, never>, Record<never, never>>,
    '/examples/input': RouteRecordInfo<'/examples/input', '/examples/input', Record<never, never>, Record<never, never>>,
    '/examples/modal': RouteRecordInfo<'/examples/modal', '/examples/modal', Record<never, never>, Record<never, never>>,
    '/examples/pagination': RouteRecordInfo<'/examples/pagination', '/examples/pagination', Record<never, never>, Record<never, never>>,
    '/examples/progress': RouteRecordInfo<'/examples/progress', '/examples/progress', Record<never, never>, Record<never, never>>,
    '/examples/radio': RouteRecordInfo<'/examples/radio', '/examples/radio', Record<never, never>, Record<never, never>>,
    '/examples/switch': RouteRecordInfo<'/examples/switch', '/examples/switch', Record<never, never>, Record<never, never>>,
    '/examples/tab': RouteRecordInfo<'/examples/tab', '/examples/tab', Record<never, never>, Record<never, never>>,
    '/examples/table': RouteRecordInfo<'/examples/table', '/examples/table', Record<never, never>, Record<never, never>>,
    '/examples/textarea': RouteRecordInfo<'/examples/textarea', '/examples/textarea', Record<never, never>, Record<never, never>>,
    '/examples/title': RouteRecordInfo<'/examples/title', '/examples/title', Record<never, never>, Record<never, never>>,
    '/examples/tooltip': RouteRecordInfo<'/examples/tooltip', '/examples/tooltip', Record<never, never>, Record<never, never>>,
    '/examples/tree': RouteRecordInfo<'/examples/tree', '/examples/tree', Record<never, never>, Record<never, never>>,
  }
}
